# Generated by Django 3.1.7 on 2021-03-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='barcodeImage',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='barcodeNumber',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
