# Generated by Django 3.1.7 on 2021-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_productmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
