# Generated by Django 3.1.7 on 2021-04-01 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_auto_20210402_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
