# Generated by Django 3.1.7 on 2021-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20210402_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
