# Generated by Django 3.1.7 on 2021-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_productmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
