# Generated by Django 3.1.7 on 2021-04-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_stockmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='admins.productmodel'),
        ),
    ]
